services:
    lordbeaver.chevereto.listener:
        class: lordbeaver\chevereto\event\listener
        arguments:
            - '@cache.driver'
            - '@config'
            - '@files.factory'
            - '@log'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
